project:
  type: website
  output-dir: "docs"

website: 
  title: "PPR Fret Project"
  
  navbar: 
    right: 
      - text: "Logbook"
        href: index.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css


